### ISSUE TITLE
"About" footer sometimes blocks data for available games

### ISSUE THREAD

**Issue by cthowl01** [Moving-On-Up/team-chess-ruby#101]
When there are multiple games, the About footer can overlap with some of the data for Available games as shown in the screenshot. The footer should always be below any game data.

![image](https://user-images.githubusercontent.com/52461069/76925626-0a033c00-68a8-11ea-9816-91baf3d0b337.png)

**Comment by j1wooldridge** [comment]
Chris is this issue still happening?

**Comment by j1wooldridge** [comment]
I am closing this issue as I cant seem to recreate it
