### ISSUE TITLE
no_legal_next_move method should check for current player

### ISSUE THREAD

**Issue by cthowl01** [Moving-On-Up/team-chess-ruby#106]
Need some logic to check whose turn it is. Stalemate is when the current player has no legal next move, and the current code could return false if the nonactive player doesn't have a legal move which wouldn't be stalemate if the current player does.

`def no_legal_next_move?
    if white_player.pieces.valid_move? == false
      return false
    elsif black_player.pieces.valid_move? == false
      return false
    end   
  end `

**Comment by Yonttee** [comment]
built a no_legal_next_move? method in king.rb
